@echo off
echo Starting Whisperoom Frontend...
cd frontend
echo.
echo Checking dependencies...
if not exist node_modules (
    echo Installing dependencies...
    call npm install
)
echo.
echo Starting development server...
npm run dev

