@echo off
echo Starting Whisperoom Backend Server...
cd backend
echo.
echo Checking dependencies...
if not exist node_modules (
    echo Installing dependencies...
    call npm install
)
echo.
echo Initializing admin user...
node ensureAdmin.js
echo.
echo Starting server...
npm start

